version: "3"
services:
  metube:
    build: .
    container_name: metube
    restart: unless-stopped
    user: "1001:1001"
    ports:
      - "8081:8081"
#     volumes:
#       - ./downloads:/downloads
